# infrastructure/docker-compose.yml
services:
  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app/backend
      - ../huggingface_tasks:/app/huggingface_tasks
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      - PYTHONPATH=/app