services:
  db: 
    image: postgres:15-alpine 
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 
    environment:
      - POSTGRES_USER=smartaudit
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=smartauditops
    ports:
      - "5432:5432"

  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app/backend
      - ../huggingface_tasks:/app/huggingface_tasks
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://smartaudit:supersecret@db/smartauditops
    depends_on:
      - db 

  frontend:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend


volumes:
  postgres_data: